// cart, products
export default {
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    REMOVE_PRODUCT_TYPE_FROM_CART: 'REMOVE_PRODUCT_TYPE_FROM_CART',
    CLEAR_CART: 'CLEAR_CART'
}
